from enum import auto

from .namespace import Namespace


class SourceNamespace(Namespace):
    """
    The `Source` identifies the primary object, resource, or subsystem that the `identifier` represents (e.g., `runtime`, `data`, `workflow`).

    The optional `Component` further specializes the `Source` by identifying a specific part, implementation, or subcomponent (e.g., `agent`, `resource`, `pipeline`).

    Default namespace values used in the middle segments of an identifier.

    Group — Where does it belong?
    Source — What is it?
    Component — Which part of it?
    Action — What does it do?
    """

    # resource = auto()
    # manager = auto()
    # collection = auto()
    # bundle = auto()
    # account = auto()
    # profile = auto()
    # setting = auto()
    # config = auto()
    # option = auto()
    # data = auto()
    # design = auto()
    # script = auto()
    # dataset = auto()
    # record = auto()
    # model = auto()
    # workflow = auto()
    # pipeline = auto()
    # stack = auto()
    # activity = auto()
    # process = auto()
    # controller = auto()
    # context = auto()
    # repository = auto()
    # task = auto()
    # event = auto()
    # target = auto()
    # state = auto()
    # runtime = auto()
    # mode = auto()
    # token = auto()
    # migration = auto()
    # container = auto()
    # payload = auto()
    # engine = auto()
    # agent = auto()
    # signature = auto()
    resource = auto()
    manager = auto()
    service = auto()
    provider = auto()
    factory = auto()
    builder = auto()
    repository = auto()
    controller = auto()
    handler = auto()
    adapter = auto()
    client = auto()
    server = auto()
    data = auto()
    dataset = auto()
    record = auto()
    entity = auto()
    model = auto()
    schema = auto()
    payload = auto()
    document = auto()
    collection = auto()
    bundle = auto()
    cache = auto()
    snapshot = auto()
    runtime = auto()
    engine = auto()
    process = auto()
    task = auto()
    thread = auto()
    worker = auto()
    job = auto()
    queue = auto()
    scheduler = auto()
    context = auto()
    state = auto()
    session = auto()
    config = auto()
    setting = auto()
    option = auto()
    parameter = auto()
    rule = auto()
    profile = auto()
    environment = auto()
    connector = auto()
    gateway = auto()
    bridge = auto()
    proxy = auto()
    transport = auto()
    channel = auto()
    stream = auto()
    agent = auto()
    tool = auto()
    prompt = auto()
    memory = auto()
    embedding = auto()
    vector = auto()
    knowledge = auto()
    conversation = auto()
    identity = auto()
    credential = auto()
    token = auto()
    signature = auto()
    certificate = auto()
    permission = auto()
    role = auto()
    policy = auto()
    secret = auto()
    request = auto()
    response = auto()
    route = auto()
    middleware = auto()
    endpoint = auto()
    page = auto()
    view = auto()
    template = auto()


class CoreObjects(Namespace):
    resource = auto()
    manager = auto()
    service = auto()
    provider = auto()
    factory = auto()
    builder = auto()
    repository = auto()
    controller = auto()
    handler = auto()
    adapter = auto()
    client = auto()
    server = auto()


class Data(Namespace):
    data = auto()
    dataset = auto()
    record = auto()
    entity = auto()
    model = auto()
    schema = auto()
    payload = auto()
    document = auto()
    collection = auto()
    bundle = auto()
    cache = auto()
    snapshot = auto()


class Runtime(Namespace):
    runtime = auto()
    engine = auto()
    process = auto()
    task = auto()
    thread = auto()
    worker = auto()
    job = auto()
    queue = auto()
    scheduler = auto()
    context = auto()
    state = auto()
    session = auto()


class Configuration(Namespace):
    config = auto()
    setting = auto()
    option = auto()
    parameter = auto()
    policy = auto()
    rule = auto()
    profile = auto()
    environment = auto()


class Integration(Namespace):
    connector = auto()
    gateway = auto()
    bridge = auto()
    proxy = auto()
    transport = auto()
    endpoint = auto()
    channel = auto()
    stream = auto()


class AI(Namespace):
    agent = auto()
    tool = auto()
    prompt = auto()
    memory = auto()
    embedding = auto()
    model = auto()
    vector = auto()
    knowledge = auto()
    conversation = auto()


class Security(Namespace):
    identity = auto()
    credential = auto()
    token = auto()
    signature = auto()
    certificate = auto()
    permission = auto()
    role = auto()
    policy = auto()
    secret = auto()


class Web(Namespace):
    request = auto()
    response = auto()
    route = auto()
    middleware = auto()
    endpoint = auto()
    resource = auto()
    page = auto()
    view = auto()
    template = auto()
